### ISSUE TITLE
looks like bump action does not respect the audit error

### ISSUE THREAD

**Issue by chenrui333** [dawidd6/action-homebrew-bump-formula#21]
it looks like the action flow does not respect the audit checks, see these PRs:
- vim, https://github.com/Homebrew/homebrew-core/pull/66202, https://github.com/Homebrew/homebrew-core/pull/66228, https://github.com/Homebrew/homebrew-core/pull/66258

**Comment by dawidd6** [comment]
Running an audit involves installing a load of Ruby gems. I was trying to avoid that. If you think the audit will be useful, I'll enable it.

**Comment by carlocab** [comment]
Maybe you can avoid installing the gems by just making sure the bump action respects throttling?

Or just deactivate the bump action for throttled formulae entirely. Seems like a lot of overhead to install all these gems just to check that you haven't bumped a handful of formulae.

**Comment by dawidd6** [comment]
I'm thinking about enabling the audit only for livecheck mode of this Action. Skipping throttled formulae will be too much I think.

**Comment by carlocab** [comment]
That's okay too. 

I was just thinking that being able to automatically bump a few formulae isn't worth either firing up the audit mechanism (and installing lots of gems in the process) or working out a way to respect throttling without having to fire up an audit. After all, these formulae are throttled because they were getting bumped _too often_. I don't think excluding them from the bump action would be a huge loss.
